# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
# tests
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml


stages:
  - compil
Push DBB:
  stage: compil
  script:
  - echo "Push DBB project to USS"
  - $DBB_HOME/bin/groovyz -DBB_PERSONAL_DAEMON -Djava.library.path=/var/dbb/dbb-ztoolkit-1.1.3/lib:/usr/lib/java_runtime64 /u/ibmuser/dbb-zappbuild-2-x/build.groovy --workspace /u/ibmuser/builds/${CI_RUNNER_SHORT_TOKEN}/${CI_CONCURRENT_ID}/${CI_PROJECT_NAMESPACE} --application ${CI_PROJECT_NAME} --workDir /u/ibmuser/build/logs/BUILD-${CI_PIPELINE_ID} --hlq IBMUSER --url https://10.7.1.43:9443/dbb/ --id IBMUSER --pw sys1 --verbose --fullBuild
  tags:
    - zos-ssh
  variables:
     $CI_PIPELINE_SOURCE :
       value : "pipeline"
     CI_DEBUG_TRACE: 
       value : "true"
      
workflow:
  rules:
    - changes: 
      - README.md
      - .vscode/*
      when: never
    - when: always

#stages:
 # - init
  #- compil
   
#compilation:
 # stage: compil
  #tags:
  #  - LD034ZDT00001V  # tag référencé pour lier runner SSH et serveur cible ; on execute script sur le serveur cible
  #variables:
#        GIT_STRATEGY: none # no clone needed
   #     CI_DEBUG_TRACE: "true"
  #script:
   #  - $DBB_HOME/bin/groovyz -DBB_PERSONAL_DAEMON -Djava.library.path=/var/dbb/dbb-ztoolkit-1.1.3/lib:/usr/lib/java_runtime64 /u/ibmuser/dbb-zappbuild-2-x/build.groovy --workspace /u/ibmuser/builds/${CI_RUNNER_SHORT_TOKEN}/${CI_CONCURRENT_ID}/${CI_PROJECT_NAMESPACE} --application ${CI_PROJECT_NAME} --workDir /u/ibmuser/build/logs/BUILD-${CI_PIPELINE_ID} --hlq IBMUSER --url https://10.7.1.43:9443/dbb/ --id IBMUSER --pw sys1 --verbose --fullBuild